modLoader = "javafml"
loaderVersion = "[1,)"
license = "Mozilla Public License Version 2.0"

[[mods]]
modId = "whoisthepotato"
version = "${version}"
displayName = "WhoIsThePotato"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[mixins]]
config = "whoisthepotato.mixins.json"