modLoader = "javafml"
loaderVersion = "[36,)"
license = "Mozilla Public License Version 2.0"

[[mods]]
modId = "whoisthepotato"
version = "${version}"
displayName = "WhoIsThePotato"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[dependencies.whoisthepotato]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
